// Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

// Examples: 

// Input : abc
// Output : a, b, c, ab, bc, ac, abc

#include <iostream>
using namespace std;

// Include - Exclude Pattern

void findSubsequences(string s, int ind, string output){
    
    //Base case
    if (ind >= s.length())
    {
        // ans is already built in the output string, if we reached the base case. Print it out!
        cout<< output << endl;
        return;
    }

    // take the character and make two cases, whether the character should be included or excluded
    char ch = s[ind];

    //Case 1- character not included in the output string
    findSubsequences(s, ind+1, output);

    //Case 2- character included in the output string
    output.push_back(ch);
    findSubsequences(s, ind+1, output);
    
}

int main()
{
   string s = "abc";
   int ind = 0;
   string output = "";
   findSubsequences(s, ind, output);
}